name: Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run C tests
      run: |
        cd tests/C
        make all
        ./build/basic.exe
        ./build/timestamp.exe
    - name: Run C++ tests
      run: |
        cd tests/Cpp
        make all
        ./build/basic.exe
        ./build/timestamp.exe
